server:
  #  \u6CE8\u518C\u4E2D\u5FC3\u7684\u7AEF\u53E3
  port: 8761

spring:
  application:
    # \u5E94\u7528\u540D\u79F0\uFF0C\u4F1A\u5728Eureka\u4E2D\u4F5C\u4E3A\u670D\u52A1\u7684id\u6807\u8BC6\uFF08serviceId\uFF09
    name: eureka-server

# 注册中心配置
eureka:
  server:
    # 关闭Eureka的自我保护模式；建议只在开发环境中使用
    enable-self-preservation: false
  instance:
    # 主机名称
    hostname: localhost
  client:
    # 是否注册到服务器。因为他本身就是服务器，所以无需注册到服务器
    register-with-eureka: false
    # 是否获取注册中心的注册信息
    fetch-registry: false
    serviceUrl:
      # http://${eureka.instance.hostname}:${server.port}/eureka/ 自己作为服务器，公布出来的地址。
      # 比如后续某个微服务要把自己注册到 eureka server, 那么就要使用这个地址：http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/