server:
  port: 8041
  servlet:
    encoding:
      charset: utf-8
      force: false
spring:
#  application:
#    name: aservice-rbac
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8


