server:
  port: 8042
  servlet:
    encoding:
      charset: utf-8
      force: false
spring:
  application:
    name: aservice-sms
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

        

