server:
  port: 8777

spring:
  application:
    name: server-gateway
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      routes:
        - id: test # 路由的编号
          uri: http://www.iocoder.cn # 路由到的目标地址
          predicates:
            - Path=/blog # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
          filters:
            - StripPrefix=1 # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
        - id: oschina
          uri: https://www.oschina.net
          predicates:
            - Path=/oschina
          filters:
            - StripPrefix=1 # 对应的具体实现是 `StripPrefixGatewayFilterFactory`，可以接收一个非负整数，作用是去掉url的层数，整数即对应层数。